build: 📦 fix firebase deploy
Error: @google-cloud/pubsub tried to access @grpc/grpc-js, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @grpc/grpc-js